### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bynov** [JustinObanor/lets_Go#2]
1. You need to parse "Europe/Minsk" location, not "UTC". You need to specify destination location, not source location. [Line](https://github.com/JustinObanor/lets_Go/blob/master/kufar/books/main.go#L68)
2. Please avoid parsing some stuff on every function call. It's better here to make a global var with location. [Line](https://github.com/JustinObanor/lets_Go/blob/master/kufar/books/main.go#L68)
3. It's better to create a function, that will convert one to one, not a slice to slice `validateResponse(books Book) BookResponse`. In that case you can reuse it in your `ReadBook` method.
4. You can easily work with `Database`, not with `*Database` here because you are not making some changes in your `Database` object. Try to use copying as much as possible in simple cases. [Link](https://github.com/JustinObanor/lets_Go/blob/master/kufar/books/main.go#L101)
5. Please check errors returned from all functions :)
6. Try to use constants instead of "magic" numbers :) For example use `http.StatusInternalServerError` instead of [Link](https://github.com/JustinObanor/lets_Go/blob/master/kufar/books/main.go#L132)
7. By default, if you are using `time.Now()` it will return a current time in your machine timezone. To avoid any future errors it's better to specify UTC like `time.Now().UTC()`.
8.  Please change `validateResponse` function name, because it's not a validation. You need to create a meaningful name. Something like `convertToResponse`.

**Comment by JustinObanor** [comment]
Closes #2

**Comment by JustinObanor** [comment]
closes #2
